import { defineSlotRecipe } from "@pandacss/dev";

export const cartSummary = defineSlotRecipe({
  className: "cart-summary",
  slots: [
    "root",
    "title",
    "row",
    "rowLabel",
    "rowValue",
    "divider",
    "totalRow",
    "totalLabel",
    "totalValue",
    "checkoutButton",
    "continueLink",
    "features",
    "feature",
  ],
  base: {
    root: {
      padding: "2.5rem",
      bg: "{colors.sand.pale}",
      border: "1px solid {colors.sand}",
      position: "sticky",
      top: "6rem",
    },
    title: {
      fontFamily: "display",
      fontSize: "1.8rem",
      fontWeight: "400",
      marginBottom: "2rem",
      color: "{colors.espresso}",
    },
    row: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: "1rem",
    },
    rowLabel: {
      fontSize: "0.8rem",
      letterSpacing: "0.1em",
      color: "{colors.espresso.soft}",
      textTransform: "uppercase",
    },
    rowValue: {
      fontFamily: "display",
      fontSize: "1rem",
      color: "{colors.espresso}",
    },
    divider: {
      height: "1px",
      bg: "{colors.sand}",
      marginTop: "1.5rem",
      marginBottom: "1.5rem",
    },
    totalRow: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "baseline",
      marginBottom: "2rem",
    },
    totalLabel: {
      fontSize: "0.7rem",
      letterSpacing: "0.25em",
      textTransform: "uppercase",
      color: "{colors.espresso}",
    },
    totalValue: {
      fontFamily: "display",
      fontSize: "2rem",
      fontWeight: "400",
      color: "{colors.espresso}",
    },
    checkoutButton: {
      width: "100%",
      padding: "1.1rem",
      bg: "{colors.espresso}",
      color: "{colors.sand.light}",
      fontFamily: "body",
      fontSize: "0.7rem",
      letterSpacing: "0.25em",
      textTransform: "uppercase",
      border: "none",
      cursor: "pointer",
      display: "block",
      textAlign: "center",
      textDecoration: "none",
      transition: "all 0.3s ease",
      position: "relative",
      overflow: "hidden",
      _hover: {
        bg: "{colors.gold}",
      },
    },
    continueLink: {
      display: "block",
      textAlign: "center",
      marginTop: "1rem",
      fontSize: "0.7rem",
      letterSpacing: "0.15em",
      textTransform: "uppercase",
      color: "{colors.espresso.soft}",
      textDecoration: "none",
      transition: "color 0.3s ease",
      _hover: {
        color: "{colors.gold}",
      },
    },
    features: {
      marginTop: "2rem",
      paddingTop: "2rem",
      borderTop: "1px solid {colors.sand}",
      display: "flex",
      flexDirection: "column",
      gap: "0.8rem",
    },
    feature: {
      display: "flex",
      alignItems: "center",
      gap: "0.8rem",
      fontSize: "0.75rem",
      color: "{colors.espresso.soft}",
      "& svg": {
        width: "16px",
        height: "16px",
        color: "{colors.gold}",
        flexShrink: "0",
      },
    },
  },
});
