import { defineSlotRecipe } from "@pandacss/dev";

export const productDetail = defineSlotRecipe({
  className: "product-detail",
  slots: [
    "root",
    "grid",
    "gallery",
    "mainImage",
    "thumbnails",
    "thumb",
    "info",
    "type",
    "name",
    "price",
    "divider",
    "description",
    "optionLabel",
    "colorRow",
    "colorSwatch",
    "quantityRow",
    "addButton",
    "secondaryActions",
    "secLink",
    "accordion",
    "accItem",
    "accHeader",
    "accIcon",
    "accBody",
  ],
  base: {
    root: {
      maxWidth: "1400px",
      marginLeft: "auto",
      marginRight: "auto",
      padding: "2rem 4rem 8rem",
      "@media (max-width: 1024px)": {
        padding: "2rem 2rem 6rem",
      },
      "@media (max-width: 640px)": {
        padding: "1.5rem 1.5rem 5rem",
      },
    },
    grid: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: "6rem",
      alignItems: "start",
      "@media (max-width: 1024px)": {
        gridTemplateColumns: "1fr",
        gap: "3rem",
      },
    },
    gallery: {
      position: "sticky",
      top: "6rem",
    },
    mainImage: {
      aspectRatio: "3/4",
      position: "relative",
      overflow: "hidden",
      marginBottom: "1rem",
      bg: "{colors.sand.light}",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      "& img": {
        width: "70%",
        height: "70%",
        objectFit: "contain",
        filter: "drop-shadow({shadows.productDropLg})",
        transition: "transform 0.6s ease",
      },
      "& img:hover": {
        transform: "scale(1.03)",
      },
    },
    thumbnails: {
      display: "grid",
      gridTemplateColumns: "repeat(4, 1fr)",
      gap: "0.8rem",
    },
    thumb: {
      aspectRatio: "1",
      bg: "{colors.sand.light}",
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      border: "1px solid transparent",
      transition: "all 0.3s ease",
      overflow: "hidden",
      "& img": {
        width: "70%",
        height: "70%",
        objectFit: "contain",
      },
      _hover: {
        borderColor: "{colors.gold}",
      },
    },
    info: {
      paddingTop: "1rem",
    },
    type: {
      fontSize: "0.7rem",
      letterSpacing: "0.3em",
      textTransform: "uppercase",
      color: "{colors.gold}",
      marginBottom: "1rem",
    },
    name: {
      fontFamily: "display",
      fontSize: "clamp(2rem, 3vw, 3rem)",
      fontWeight: "300",
      lineHeight: "1.1",
      color: "{colors.espresso}",
      marginBottom: "1.5rem",
    },
    price: {
      fontFamily: "display",
      fontSize: "2rem",
      color: "{colors.gold}",
      marginBottom: "2rem",
    },
    divider: {
      height: "1px",
      bg: "{colors.sand}",
      marginTop: "2rem",
      marginBottom: "2rem",
    },
    description: {
      fontSize: "0.9rem",
      lineHeight: "1.8",
      color: "{colors.espresso.soft}",
      marginBottom: "2rem",
    },
    optionLabel: {
      fontSize: "0.65rem",
      letterSpacing: "0.25em",
      textTransform: "uppercase",
      color: "{colors.espresso}",
      marginBottom: "1rem",
    },
    colorRow: {
      display: "flex",
      gap: "0.8rem",
      marginBottom: "2rem",
      flexWrap: "wrap",
    },
    colorSwatch: {
      width: "32px",
      height: "32px",
      borderRadius: "50%",
      cursor: "pointer",
      border: "2px solid transparent",
      transition: "all 0.3s ease",
      _hover: {
        transform: "scale(1.15)",
      },
    },
    quantityRow: {
      display: "flex",
      alignItems: "center",
      gap: "1.5rem",
      marginBottom: "2rem",
    },
    addButton: {
      flex: "1",
      padding: "1.1rem",
      bg: "{colors.espresso}",
      color: "{colors.sand.light}",
      fontFamily: "body",
      fontSize: "0.7rem",
      letterSpacing: "0.25em",
      textTransform: "uppercase",
      border: "none",
      cursor: "pointer",
      transition: "all 0.4s ease",
      position: "relative",
      overflow: "hidden",
      _before: {
        content: '""',
        position: "absolute",
        top: "0",
        left: "-100%",
        width: "100%",
        height: "100%",
        bg: "{colors.gold}",
        transition: "left 0.4s ease",
      },
      _hover: {
        _before: {
          left: "0",
        },
      },
      "& span": {
        position: "relative",
        zIndex: "1",
      },
    },
    secondaryActions: {
      display: "flex",
      gap: "2rem",
      marginBottom: "2rem",
    },
    secLink: {
      fontSize: "0.7rem",
      letterSpacing: "0.15em",
      textTransform: "uppercase",
      color: "{colors.espresso.soft}",
      textDecoration: "none",
      display: "flex",
      alignItems: "center",
      gap: "0.5rem",
      transition: "color 0.3s ease",
      bg: "transparent",
      border: "none",
      cursor: "pointer",
      fontFamily: "body",
      padding: "0",
      _hover: {
        color: "{colors.gold}",
      },
      "& svg": {
        width: "16px",
        height: "16px",
      },
    },
    accordion: {
      borderTop: "1px solid {colors.sand}",
    },
    accItem: {
      borderBottom: "1px solid {colors.sand}",
    },
    accHeader: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: "1.2rem 0",
      cursor: "pointer",
      fontSize: "0.7rem",
      letterSpacing: "0.2em",
      textTransform: "uppercase",
      color: "{colors.espresso}",
      bg: "transparent",
      border: "none",
      width: "100%",
      textAlign: "left",
      fontFamily: "body",
      transition: "color 0.3s ease",
      _hover: {
        color: "{colors.gold}",
      },
    },
    accIcon: {
      fontSize: "1.2rem",
      transition: "transform 0.3s ease",
      color: "{colors.gold}",
    },
    accBody: {
      overflow: "hidden",
      transition: "max-height 0.4s ease",
      "& p": {
        paddingBottom: "1.5rem",
        fontSize: "0.85rem",
        lineHeight: "1.8",
        color: "{colors.espresso.soft}",
      },
    },
  },
  variants: {
    thumbActive: {
      true: {
        thumb: {
          borderColor: "{colors.gold}",
        },
      },
    },
    accOpen: {
      true: {
        accIcon: {
          transform: "rotate(45deg)",
        },
      },
    },
  },
});
