import { defineTokens } from "@pandacss/dev";

export const tokens = defineTokens({
  colors: {
    sand: {
      DEFAULT: { value: "#E8DFD0" },
      light: { value: "#F4EDE3" },
      pale: { value: "#FAF7F2" },
    },
    espresso: {
      DEFAULT: { value: "#2C1810" },
      soft: { value: "#4A3228" },
    },
    gold: {
      DEFAULT: { value: "#B8956A" },
      light: { value: "#D4B896" },
      bright: { value: "#C9A87C" },
    },
    cream: { value: "#FFFCF7" },
    sage: { value: "#8B9A7E" },
    terracotta: { value: "#C2785C" },
    charcoal: { value: "#1A1A1A" },
    white: { value: "#FFFFFF" },
    transparent: { value: "transparent" },
  },
  fonts: {
    display: { value: "'Cormorant Garamond', serif" },
    body: { value: "'Outfit', sans-serif" },
  },
  fontSizes: {
    xs: { value: "0.55rem" },
    sm: { value: "0.65rem" },
    caption: { value: "0.7rem" },
    "body.sm": { value: "0.85rem" },
    body: { value: "0.95rem" },
    "body.md": { value: "1rem" },
    "body.lg": { value: "1.1rem" },
    "heading.sm": { value: "1.3rem" },
    "heading.md": { value: "1.5rem" },
    "heading.lg": { value: "1.8rem" },
    "heading.xl": { value: "clamp(2.2rem, 3.5vw, 3.5rem)" },
    "heading.hero": { value: "clamp(3rem, 5.5vw, 5.5rem)" },
    display: { value: "8rem" },
  },
  fontWeights: {
    extraLight: { value: "200" },
    light: { value: "300" },
    regular: { value: "400" },
    medium: { value: "500" },
    semibold: { value: "600" },
  },
  letterSpacings: {
    tight: { value: "0.08em" },
    normal: { value: "0.1em" },
    relaxed: { value: "0.12em" },
    wide: { value: "0.15em" },
    wider: { value: "0.2em" },
    widest: { value: "0.25em" },
    editorial: { value: "0.3em" },
    display: { value: "0.35em" },
    ultra: { value: "0.4em" },
  },
  lineHeights: {
    none: { value: "1" },
    tight: { value: "1.05" },
    snug: { value: "1.15" },
    normal: { value: "1.6" },
    relaxed: { value: "1.8" },
    loose: { value: "1.9" },
  },
  spacing: {
    "0.5": { value: "0.3rem" },
    "1": { value: "0.5rem" },
    "1.5": { value: "0.8rem" },
    "2": { value: "1rem" },
    "3": { value: "1.5rem" },
    "4": { value: "2rem" },
    "5": { value: "2.5rem" },
    "6": { value: "3rem" },
    "7": { value: "4rem" },
    "8": { value: "5rem" },
    "10": { value: "6rem" },
    "12": { value: "8rem" },
    "16": { value: "10rem" },
  },
  sizes: {
    "content.sm": { value: "500px" },
    "content.md": { value: "600px" },
    "content.lg": { value: "700px" },
    "content.xl": { value: "900px" },
    "content.full": { value: "1300px" },
    container: { value: "1400px" },
  },
  shadows: {
    nav: { value: "0 1px 0 rgba(184, 149, 106, 0.15)" },
    cardHover: { value: "0 20px 60px rgba(184, 149, 106, 0.1)" },
    productDrop: { value: "0 15px 40px rgba(44, 24, 16, 0.15)" },
    productDropLg: { value: "0 25px 60px rgba(44, 24, 16, 0.2)" },
    heroBag: { value: "0 20px 60px rgba(44, 24, 16, 0.2)" },
    notification: { value: "0 10px 40px rgba(44, 24, 16, 0.2)" },
    cartItem: { value: "0 5px 15px rgba(44, 24, 16, 0.12)" },
  },
  zIndex: {
    base: { value: "1" },
    content: { value: "2" },
    nav: { value: "1000" },
    menuToggle: { value: "1001" },
    notification: { value: "2000" },
    grain: { value: "9000" },
    cursorRing: { value: "9998" },
    cursorDot: { value: "9999" },
    preloader: { value: "10000" },
  },
  radii: {
    sm: { value: "1px" },
    md: { value: "4px" },
    lg: { value: "8px" },
    full: { value: "50%" },
  },
  durations: {
    fast: { value: "0.15s" },
    normal: { value: "0.3s" },
    medium: { value: "0.4s" },
    slow: { value: "0.5s" },
    slower: { value: "0.8s" },
  },
  easings: {
    default: { value: "ease" },
    reveal: { value: "cubic-bezier(0.16, 1, 0.3, 1)" },
  },
});
